import { IPage } from "./IPage";
import { ITodoListTasks } from "./ITodoListTasks";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageITodoListTasks = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ITodoListTasks[];
};
